version: '2.1'

services:
    tm1:
        build:
            context: docker
            dockerfile: Dockerfile-tema2
        privileged: true
        depends_on:
            - "tm2"
        command: bash -c "echo 'ok' & python ./elocal/src/udp_client.py -s tm2 -p 10000 -m 'mesaj' "
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
    tm2:
        build:
            context: docker
            dockerfile: Dockerfile-tema2
        privileged: true
        command: bash -c "tcpdump -nn -vvv ip and udp & python ./elocal/src/udp_server.py -p 10000 "
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz

networks:
    dmz: {}
