version: '2.1'

services:
    rt1:
        image: 233:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
            - net
        sysctls:
            - net.ipv4.icmp_echo_ignore_all=1
    rt2:
        image: 233:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - net
    rt3:
        image: 233:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz

networks:
    dmz:
        ipam:
            driver: default
            config:
                - subnet: 172.111.111.0/16 
                  gateway: 172.111.111.1
    net:
        ipam:
            driver: default
            config:
                - subnet: 198.13.13.0/16
                  gateway: 198.13.13.1
