version: '2.1'

services:
    rt1:
        image: 233:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
    rt2:
        image: 233:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
    rt3:
        image: 233:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz

networks:
    dmz: {}
